import 'dotenv/config';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { createClient } from '@supabase/supabase-js';
import { renderPdfWithXeLatex } from './src/problem_bank/render_engine/xelatex_v2/renderer.js';
const supa=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const doc='66dce0c9-36c9-46b6-9a9c-648340f86bca';
const {data:questions,error}=await supa.from('pb_questions').select('*').eq('document_id',doc).in('question_number',['15','16','17','18','19','20']).order('question_number');
if(error) throw error;
await renderPdfWithXeLatex({questions,paper:'a4',profile:'mock',supabaseClient:supa,fontFamilyResolved:'Malgun Gothic'});
const tmp=os.tmpdir();
const dirs=fs.readdirSync(tmp).filter(d=>d.startsWith('pb-xelatex-doc-')).map(d=>({d,t:fs.statSync(path.join(tmp,d)).mtimeMs})).sort((a,b)=>b.t-a.t);
const pdf=path.join(tmp,dirs[0].d,'document.pdf');
execFileSync('pdftoppm',['-png','-r','130',pdf,'C:/Users/harry/Yggdrasill/dongdo3_mock_common_width']);
console.log('pdf',pdf);
console.log(fs.readdirSync('C:/Users/harry/Yggdrasill').filter(f=>f.startsWith('dongdo3_mock_common_width')).join(','));
process.exit(0);
