// VLM(PDF) 추출 엔진용 Gemini 프롬프트.
//
// 이 파일은 기존 실험 스크립트 scripts/vlm_extract_experiment.mjs 에서 사용하던
// buildPrompt() 를 운영 워커(problem_bank_extract_worker.js) 에서 재사용할 수 있도록
// ESM 모듈로 분리한 것이다. 출력 JSON 스키마와 stem 포맷 규약은 매니저/렌더러가
// 이미 가정하는 규약이므로 여기서 변경하지 말 것.

export function buildPrompt({ textbookScope = null } = {}) {
  const scope = textbookScope && typeof textbookScope === 'object'
    ? textbookScope
    : null;
  const scopeLines = scope
    ? [
        '=== 교재 소단원 추출 범위 ===',
        `이 작업은 전체 PDF 중 한 소단원만 문제은행 문서로 추출한다.`,
        `범위: 대단원 ${scope.big_order ?? ''}, 중단원 ${scope.mid_order ?? ''}, 소단원 ${scope.sub_key ?? ''}`,
        `이름: ${scope.big_name || ''} / ${scope.mid_name || ''} / ${scope.sub_name || ''}`,
        `페이지 범위(raw/display): ${scope.raw_page_from ?? ''}~${scope.raw_page_to ?? ''} / ${scope.display_page_from ?? ''}~${scope.display_page_to ?? ''}`,
        '첨부된 PDF는 위 raw page 범위만 잘라낸 사본일 수 있다.',
        'questions[].source_page 는 첨부 사본 기준이 아니라 원본 본문 PDF 의 raw page 번호로 적어라.',
        '위 범위 밖의 문항은 questions 에 넣지 마라.',
        '',
      ]
    : [];
  return [
    '당신은 한국 중·고등학교 수학 시험지 PDF 를 분석해 문항을 "Yggdrasill stem 포맷" 의 구조화 JSON 으로 추출하는 AI 입니다.',
    '반드시 다음 JSON 스키마만 출력합니다. 설명 문장·마크다운 금지. JSON 외 어떤 텍스트도 출력하지 마세요.',
    '',
    ...scopeLines,
    '=== 출력 스키마 ===',
    '{',
    '  "document_meta": {',
    '    "total_questions": <정수>,',
    '    "page_count": <정수>,',
    '    "confidence": "high" | "medium" | "low"',
    '  },',
    '  "questions": [',
    '    {',
    '      "question_number": "1",',
    '      "source_page": 1,',
    '      "stem": "Yggdrasill stem 포맷 문자열 — 아래 === STEM 포맷 규칙 === 준수",',
    '      "question_type": "객관식" | "주관식" | "서술형",',
    '      "is_set_question": false,',
    '      "sub_questions": [ { "label": "(1)", "text": "소문항 본문 (stem 과 동일한 포맷)", "score": <실수 또는 null> } ],',
    '      "choices": [ { "label": "①", "text": "선택지 본문 (stem 과 동일한 포맷)" } ],',
    '      "answer": {',
    '        "objective_key": "① 또는 ②, ③",',
    '        "subjective": "정답 문자열 (세트형은 \\"(1) 12 (2) ㄱ, ㄷ\\" 형식)",',
    '        "parts": [ { "sub": "1", "value": "12" }, { "sub": "2", "value": "ㄱ, ㄷ" } ]',
    '      },',
    '      "score": <실수 또는 null>,',
    '      "figures": [ { "order": 1, "description": "그림 간단 설명" } ],',
    '      "tables":  [ { "order": 1, "rows": <정수>, "cols": <정수>, "has_diagonal_cell": <bool>, "description": "표 간단 설명", "rendered_as": "tabular" | "image" } ],',
    '      "flags": [ "contains_figure" | "contains_table" | "contains_box" | "contains_view_block" ],',
    '      "uncertain_fields": [ "choices" | "answer" | "figures" | "tables" | "stem" | "..." ]',
    '    }',
    '  ]',
    '}',
    '',
    '=== STEM 포맷 규칙 (매우 중요) ===',
    '아래 stem/choices/answer 포맷은 문제은행 카드, 서버 PDF 미리보기, 최종 PDF 출력이 공통으로 사용하는 XeLaTeX 렌더러 규약이다.',
    '따라서 화면 표시용 임의 마크다운이나 자연어 설명을 섞지 말고, 렌더러가 그대로 소비할 수 있는 구조만 남겨라.',
    '[S0] 스캔 문장이 어색해 보여도 보이는 원문을 그대로 옮긴다. 조사/어미를 임의로 고치거나 더 자연스러운 수학 용어로 바꾸지 마라.',
    '     예: 이미지에 "다음을 거듭제곱을" 로 보이면 "다음 거듭제곱근을" 로 교정하지 말고 보이는 그대로 둔다.',
    '[S1] 수식은 LaTeX 명령만 사용하되 "delimiter 를 쓰지 마라" (\\( \\) / \\[ \\] / $ / $$ 전부 금지).',
    '     예) 올바른: "a + \\frac{b}{c} = 3"     잘못된: "\\(a + \\frac{b}{c}\\) = 3"  /  "$a+\\frac{b}{c}$"',
    '[S2] 곱셈 기호는 "\\times", 나눗셈은 "\\div", ±는 "\\pm", ≤≥≠는 "\\leq","\\geq","\\neq" 로만 표기. 알파벳 x / ÷ / ± 문자 직접 사용 금지.',
    '[S3] 분수는 반드시 "\\frac{a}{b}" 형태. "a/b" 같은 슬래시 분수 금지 (단, 정답 문자열은 허용).',
    '[S4] 본문 중간에 등장하는 모든 그림·도형은 해당 위치에 "[그림]" 마커를 삽입해 자리를 잡아라. 여러 개면 각각 "[그림]" 을 삽입.',
    '     stem 내부에서 그림을 언급할 때 "[그림1]", "[그림2]" 같은 참조 문구가 실제 인쇄돼 있으면 그대로 유지하되, 그림 자체가 있던 자리에도 별도로 "[그림]" 을 넣는다.',
    '     단, □/▢/빈칸 네모/네모칸/blank box 처럼 값을 채우는 빈칸은 그림이 아니다. stem 에는 "[그림]" 대신 "box{~~}" 로 적고 figures/flags.contains_figure 에 넣지 마라.',
    '[S5] 본문 중간에 등장하는 모든 "표" 는 해당 위치를 다음 중 하나로 표기한다:',
    '     (a) 단순 행/열 표 (대각선 셀·병합 셀 없음, 텍스트·숫자·수식만)  → "[표시작]" ... "[표끝]" 사이에 LaTeX tabular 로 재현한다.',
    '         cellspec 은 "|c|c|..." 처럼 모든 열을 c 정렬로 둔다. \\\\begin{tabular}...\\\\end{tabular} 전체를 넣어라.',
    '         ★ tabular 셀 안에 수식 명령(\\\\times, \\\\frac, \\\\pm, \\\\leq ...) 이 있으면 그 셀을 반드시 "$...$" 로 감싸라.',
    '         ★ tabular 셀 안에 한글이 있으면 그 셀을 반드시 "\\\\text{...}" 로 감싸라 (예: "\\\\text{자연수}").',
    '         ★ 빈 셀이나 단순 숫자/기호 (○, ×, -, +, 3, 0.5) 는 감싸지 않아도 된다.',
    '         예시: "[표시작]\\n\\\\begin{tabular}{|c|c|c|}\\n\\\\hline\\n\\\\text{수의 분류} & 3 & -3 \\\\\\\\\\n\\\\hline\\n\\\\text{자연수} & ○ & $\\\\times$ \\\\\\\\\\n\\\\hline\\n\\\\end{tabular}\\n[표끝]"',
    '     (b) 대각선 셀을 가진 표, 여러 셀 병합, 도형 삽입 같은 복잡한 표  → tabular 로 재현 불가. "[그림]" 마커 하나만 남겨 이미지로 처리한다는 신호.',
    '         또한 해당 questions[].tables[i].rendered_as 를 "image" 로 세팅한다.',
    '[S6] 문단 구분은 개행 또는 "[문단]" 마커로 표기 (렌더러가 여백을 잡는다). 불필요하게 많이 쓰지 말 것.',
    '[S7] 보기 박스 (<보기> 또는 <보 기>) 는 "[보기시작]" ... "[보기끝]" 사이에 본문을 그대로 담는다.',
    '     조건·규칙 박스(보기 아님)는 "[박스시작]" ... "[박스끝]" 사이에 담는다. 두 마커를 혼동하지 말 것.',
    '[S8] 세트형(하위문항 (1),(2),... 로 구성) 은 다음 규칙을 지킨다:',
    '     - is_set_question = true, sub_questions 배열에 각 소문항을 채운다.',
    '     - 문제 번호와 붙어 보이는 "(1)", "(2)" 같은 하위문항 번호는 절대 대표 problem_number 에 합치지 않는다.',
    '     - sub_questions[i].text 는 "(1)" 같은 레이블을 제외한 "본문만" 담는다. 레이블은 label 필드로 분리.',
    '     - stem 에는 공통 도입 문장만 남긴다 ("물음에 답하시오." 가 있으면 유지).',
    '     - answer.parts 는 각 소문항 정답, answer.subjective 는 화면 표시용 전체 문자열 "(1) X (2) Y".',
    '     - 배점: 각 소문항 옆이나 대표 문항 번호 옆에 "[N점]" 이 따로 붙어 있으면 sub_questions[i].score 에 그 숫자를 넣는다.',
    '       예) "(1) ... [3점]"  →  sub_questions[0].score = 3 ',
    '       문항 대표 배점 "[10점]" 만 보이고 소문항별 배점이 없다면 sub_questions[i].score 는 모두 null 로 두고 score(문항 총점)에만 10 을 넣는다.',
    '       세트형에서 소문항별 배점이 하나라도 잡히면 score(문항 총점)는 그 합과 일치시키거나, 합이 확정되지 않으면 null 로 둔다.',
    '[S9] 객관식 선택지 ①~⑤ 는 choices 에 순서대로 담고 answer.objective_key 에 정답 번호를 넣는다. 복수 정답이면 "②, ③" 처럼 쉼표로 모두 적고, 정답을 모르면 "".',
    '[S10] 배점 "[N점]" 이 문제 번호 옆에 있으면 score=N (실수), 없으면 null.',
    '[S11] 판단이 불확실한 필드는 uncertain_fields 에 필드명을 넣고, 추측 값 대신 빈 값("" / null / [])으로 둔다.',
    '',
    '=== 문항 수 / 범위 규칙 ===',
    '[R1] PDF 에 실제로 인쇄된 문항만 추출 (해설/풀이 페이지 제외).',
    '[R2] document_meta.total_questions 는 questions 배열 길이와 반드시 일치.',
    '[R3] 문항 번호는 시험지 상 번호(1, 2, 3...) 그대로.',
    '',
    '=== JSON 이스케이프 규칙 (반드시 지킬 것) ===',
    '[E1] JSON 문자열 안의 LaTeX 백슬래시 "\\" 는 "\\\\" 로 이스케이프해야 한다. 즉 출력 JSON 에서',
    '     "stem": "\\\\frac{1}{2}" / "\\\\times" / "\\\\leq" 처럼 한 번 더 백슬래시를 넣어라.',
    '     "\\frac" 처럼 1 개만 쓰면 JSON 파서 실패한다.',
    '[E2] 줄바꿈은 "\\n" 으로 작성하라 (JSON 리터럴 "\\\\n" 이 아니라 실제 개행 이스케이프).',
    '',
    '=== 예시 (형식만 참고, 실제 문제는 PDF 에 있는 것만 추출) ===',
    'stem 예시 A (그림 없음, 분수 있음):  "두 분수 \\frac{27}{14}, \\frac{63}{20} 의 어느 것에 곱해도 항상 자연수가 되게 하는 가장 작은 기약분수를 구하시오."',
    'stem 예시 B (표 재현):               "다음 표를 완성하여라.\\n[문단]\\n[표시작]\\n\\\\begin{tabular}{|c|c|c|}\\n\\\\hline\\na & b & c \\\\\\\\\\n\\\\hline\\n\\\\end{tabular}\\n[표끝]"',
    'stem 예시 C (그림 + 보기):           "다음 그림과 <보기> 의 설명에 대해 옳은 것을 고르시오.\\n[문단]\\n[그림]\\n[문단]\\n[보기시작]\\nㄱ. a+b>0\\nㄴ. ab<0\\n[보기끝]"',
    'stem 예시 D (세트형 공통 도입):      "다음 물음에 답하시오."  (sub_questions 에 (1)/(2) 본문 분리)',
    '',
    '지금 첨부된 PDF 를 분석해 위 스키마로만 출력하라. 반드시 stem 에 delimiter(\\(, \\[, $) 를 쓰지 말 것.',
  ].join('\n');
}
