[common]
platform = espressif32
board = m5stack-core2
framework = arduino
board_build.filesystem = littlefs
board_build.partitions = partitions_ota.csv
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -D CFG_WIFI_SSID=\"KT_WiFi_F996\"
  -D CFG_WIFI_PASSWORD=\"35d30de6e7\"
  -D CFG_MQTT_HOST=\"broker.emqx.io\"
  -D CFG_MQTT_PORT=1883
  -D CFG_ACADEMY_ID=\"3ff51b8d-3cfb-4a36-a1a1-b63aebbde677\"
  -D LV_CONF_INCLUDE_SIMPLE
  -D LV_LVGL_H_INCLUDE_SIMPLE
  -D LV_CONF_PATH=C:/Users/harry/Yggdrasill/firmware/m5stack/src/lv_conf.h
  -D LV_USE_TINY_TTF=1
  -D GITHUB_OWNER=\"How-Know\"
  -D GITHUB_REPO=\"Yggdrasill\"
lib_deps =
  m5stack/M5Unified@^0.1.15
  marvinroger/AsyncMqttClient@^0.9.0
  bblanchon/ArduinoJson@^6.21.2
  lvgl/lvgl@^8.3.11

; === 1호기 ===
[env:m5-device-001]
extends = common
upload_port = COM3
monitor_port = COM3
build_flags =
  ${common.build_flags}
  -D CFG_DEVICE_ID=\"m5-device-001\"

; === 2호기 ===
[env:m5-device-002]
extends = common
upload_port = COM7
monitor_port = COM7
build_flags =
  ${common.build_flags}
  -D CFG_DEVICE_ID=\"m5-device-002\"

; === 3호기 ===
[env:m5-device-003]
extends = common
upload_port = COM8
monitor_port = COM8
build_flags =
  ${common.build_flags}
  -D CFG_DEVICE_ID=\"m5-device-003\"

; === 4호기 ===
[env:m5-device-004]
extends = common
upload_port = COM9
monitor_port = COM9
build_flags =
  ${common.build_flags}
  -D CFG_DEVICE_ID=\"m5-device-004\"

; === 5호기 ===
[env:m5-device-005]
extends = common
upload_port = COM10
monitor_port = COM10
build_flags =
  ${common.build_flags}
  -D CFG_DEVICE_ID=\"m5-device-005\"


