// Copyright @ MyScript. All rights reserved.

#import <Foundation/Foundation.h>

@class IINKEngine;
@class IINKHandwritingGenerator;
@class IINKHandwritingResult;

/**
 * Error code used in IINKHandwritingGeneratorDelegate onError
 * @since 4.1
 */
typedef NS_ENUM(NSInteger, IINKHandwritingGeneratorError) {
    /** Generic error, refer to the `message` parameter for more information. */
    IINKHandwritingGeneratorErrorGeneric,
    /** The resource file cannot be loaded. */
    IINKHandwritingGeneratorErrorResourceNotLoaded,
    /** The generator setup has failed. */
    IINKHandwritingGeneratorErrorSetupFailed,
    /** The profile cannot be selected. */
    IINKHandwritingGeneratorErrorProfileNotSelected,
    /** The generation has failed. */
    IINKHandwritingGeneratorErrorGenerationFailed
};

/**
 * The delegate interface can be used to receive handwriting generator events.
 *
 * @see IINKHandwritingGenerator
 *
 * @since 4.1
 */
@protocol IINKHandwritingGeneratorDelegate <NSObject>

//==============================================================================
#pragma mark - Required Methods
//==============================================================================
@required

/**
 * Invoked when a partial result has been generated by the given handwriting generator.
 *
 * @param generator the handwriting generator that has produced this result.
 * @param result the handwriting result.
 */
- (void)onPartialResult:(nonnull IINKHandwritingGenerator *)generator
                 result:(nonnull IINKHandwritingResult *)result;

/**
 * Invoked when a handwriting generation has ended.
 *
 * @param generator the associated handwriting generator.
 */
- (void)onEnd:(nonnull IINKHandwritingGenerator *)generator;

/**
 * Invoked when an error occurs during the handwriting generation.
 *
 * @param generator the associated handwriting generator.
 * @param code the error code.
 * @param message the error message.
 */
- (void)onError:(nonnull IINKHandwritingGenerator *)generator
        code:(IINKHandwritingGeneratorError)code
        message:(nonnull NSString *)message;

/**
 * Invoked when a label contains an unsupported character for a handwriting generation.
 *
 * @param generator the associated handwriting generator.
 * @param label the text to generate.
 * @param character the unsupported character.
 * @param index the position in glyph (i.e. grapheme cluster) count in the label of the unsupported character.
 */
- (void)onUnsupportedCharacter:(nonnull IINKHandwritingGenerator *)generator
                         label:(nonnull NSString *)label
                     character:(nonnull NSString *)character
                         index:(NSInteger)index;

@end
