// Copyright @ MyScript. All rights reserved.

#import <Foundation/Foundation.h>
#import <iink/IINKMimeType.h>
#import <iink/IINKPointerEvent.h>
#import <iink/graphics/IINKTransform.h>

@class IINKEngine;
@class IINKHandwritingProfile;
@class IINKParameterSet;
@class IINKHandwritingResult;


/**
 * Represents a handwriting result generated by a handwriting generator.
 *
 * @see IINKHandwritingGenerator
 *
 * @since 4.1
 */
@interface IINKHandwritingResult : NSObject
{

}

/**
 * The pointer events representing this handwriting result.
 *
 * @param viewTransform the view transform used to transform the result from
 *   millimeters to another coordinate system.
 * @param error the recipient for the error description object
 *  * IINKErrorInvalidArgument when `viewTransform` is not valid for this operation.
 * @return a vector of pointer events.
 */
- (nullable NSArray<IINKPointerEventValue*> *)toPointerEvents:(nonnull IINKTransform *)viewTransform
                                               error:(NSError * _Nullable * _Nullable)error
                                         NS_SWIFT_NAME(toPointerEvents(viewTransform:));

@end
